# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pip install ruamel.yaml && python3 sync.py
# to regenerate this file.

name: PR Check - Extractor ram and threads options test
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
    - main
    - releases/v1
    - releases/v2
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
  workflow_dispatch: {}
jobs:
  extractor-ram-threads:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          version: latest
    name: Extractor ram and threads options test
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Prepare test
      id: prepare-test
      uses: ./.github/prepare-test
      with:
        version: ${{ matrix.version }}
    - uses: ./../action/init
      with:
        languages: java
        ram: 230
        threads: 1
    - name: Assert Results
      shell: bash
      run: |
        if [ "${CODEQL_RAM}" != "230" ]; then
          echo "CODEQL_RAM is '${CODEQL_RAM}' instead of 230"
          exit 1
        fi
        if [ "${CODEQL_EXTRACTOR_JAVA_RAM}" != "230" ]; then
          echo "CODEQL_EXTRACTOR_JAVA_RAM is '${CODEQL_EXTRACTOR_JAVA_RAM}' instead of 230"
          exit 1
        fi
        if [ "${CODEQL_THREADS}" != "1" ]; then
          echo "CODEQL_THREADS is '${CODEQL_THREADS}' instead of 1"
          exit 1
        fi
        if [ "${CODEQL_EXTRACTOR_JAVA_THREADS}" != "1" ]; then
          echo "CODEQL_EXTRACTOR_JAVA_THREADS is '${CODEQL_EXTRACTOR_JAVA_THREADS}' instead of 1"
          exit 1
        fi
    env:
      INTERNAL_CODEQL_ACTION_DEBUG_LOC: true
