# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pip install ruamel.yaml && python3 sync.py
# to regenerate this file.

name: 'PR Check - Go: Custom tracing'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
    - main
    - releases/v1
    - releases/v2
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
  workflow_dispatch: {}
jobs:
  go-custom-tracing:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          version: stable-20210308
        - os: macos-latest
          version: stable-20210308
        - os: windows-2019
          version: stable-20210308
        - os: ubuntu-latest
          version: stable-20210319
        - os: macos-latest
          version: stable-20210319
        - os: windows-2019
          version: stable-20210319
        - os: ubuntu-latest
          version: stable-20210809
        - os: macos-latest
          version: stable-20210809
        - os: windows-2019
          version: stable-20210809
        - os: ubuntu-latest
          version: cached
        - os: macos-latest
          version: cached
        - os: windows-2019
          version: cached
        - os: ubuntu-latest
          version: latest
        - os: macos-latest
          version: latest
        - os: windows-2019
          version: latest
        - os: windows-2022
          version: latest
        - os: ubuntu-latest
          version: nightly-latest
        - os: macos-latest
          version: nightly-latest
        - os: windows-2019
          version: nightly-latest
        - os: windows-2022
          version: nightly-latest
    name: 'Go: Custom tracing'
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Prepare test
      id: prepare-test
      uses: ./.github/prepare-test
      with:
        version: ${{ matrix.version }}
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.13.1
    - uses: ./../action/init
      with:
        languages: go
        tools: ${{ steps.prepare-test.outputs.tools-url }}
    - name: Build code
      shell: bash
      run: go build main.go
    - uses: ./../action/analyze
      env:
        TEST_MODE: true
    env:
      CODEQL_EXTRACTOR_GO_BUILD_TRACING: 'true'
      INTERNAL_CODEQL_ACTION_DEBUG_LOC: true
